# Modulo 7 - Manipolazione dei Dati con Pandas

In [ ]:
# pip install mysql-connector-python
import mysql.connector

In [ ]:
try:  
    cnx = mysql.connector.connect(user='root', password='PASSWORD_DI_GABRI',
                                  host='127.0.0.1',
                                  database='sampledb')
    cursor = cnx.cursor()
    emps = [(9001, "Jeff Russell", "sales"), # definire le righe dei dipendenti
            (9002, "Jane Boorman", "sales"),
            (9003, "Tom Heints", "sales")]
        
    query_add_emp = ("""INSERT INTO emps (empno, empname, job) VALUES (%s, %s, %s)""") # definire la query
   
    for emp in emps:     # inserire le righe dei dipendenti
        cursor.execute(query_add_emp, emp)

    salary = [(9001, 3000), # definire e inserire gli stipendi
                (9002, 2800),
                (9003, 2500)]
    query_add_salary = ("""INSERT INTO salary (empno, salary) VALUES (%s, %s)""")
    for sal in salary:
        cursor.execute(query_add_salary, sal)
    
    orders = [(2608, 9001, 35), # definire e inserire gli ordini
              (2617, 9001, 35),
              (2620, 9001, 139),
              (2621, 9002, 95),
              (2626, 9002, 218)]

    query_add_order = ("""INSERT INTO orders(pono, empno, total) VALUES (%s, %s, %s)""")
    for order in orders:
        cursor.execute(query_add_order, order)

    cnx.commit()    # rendere permanenti gli inserimenti nel database
except mysql.connector.Error as err:
    print("Error-Code:", err.errno)
    print("Error-Message: {}".format(err.msg))
finally:
    cursor.close()
    cnx.close()

In [ ]:
try:  
    cnx = mysql.connector.connect(user='root', password='PASSWORD_DI_GABRI',
                                  host='127.0.0.1',
                                  database='sampledb')
    cursor = cnx.cursor()
    query = ("SELECT * FROM emps WHERE empno > %s")
    empno = 9001
    cursor.execute(query, (empno,))
    for (empno, empname, job) in cursor:
        print("{}, {}, {}".format(empno, empname, job))
except mysql.connector.Error as err:
    print("Error-Code:", err.errno)
    print("Error-Message: {}".format(err.msg))
finally:
    cursor.close()
    cnx.close()

9002, Jane Boorman, sales
9003, Tom Heints, sales


In [ ]:
# Rispetto a prima aggiunge il salary
try:  
    cnx = mysql.connector.connect(user='root', password='PASSWORD_DI_GABRI',
                                  host='127.0.0.1',
                                  database='sampledb')
    cursor = cnx.cursor()
    query = ("""SELECT e.empno, e.empname, e.job, s.salary FROM emps e JOIN salary s ON e.empno = s.empno WHERE e.empno > %s""")
    empno = 9001
    cursor.execute(query, (empno,))
    for (empno, empname, job, salary) in cursor:
        print("{}, {}, {}, {}".format(empno, empname, job, salary))
except mysql.connector.Error as err:
    print("Error-Code:", err.errno)
    print("Error-Message: {}".format(err.msg))
finally:
    cursor.close()
    cnx.close()

9002, Jane Boorman, sales, 2800
9003, Tom Heints, sales, 2500


In [21]:
import yfinance as yf
data = []
tickers = ['TSLA', 'ORCL', 'AMZN']
for ticker in tickers:
    tkr = yf.Ticker(ticker)
    hist = tkr.history(period='5d').reset_index()
    records = hist[['Date','Close']].to_records(index=False)
    records = list(records)
    records = [(ticker, str(elem[0])[:10], round(elem[1],2)) for elem in records]
    data = data + records

In [23]:
for d in data:
    print(d)

('TSLA', '2025-05-28', np.float64(356.9))
('TSLA', '2025-05-29', np.float64(358.43))
('TSLA', '2025-05-30', np.float64(346.46))
('TSLA', '2025-06-02', np.float64(342.69))
('TSLA', '2025-06-03', np.float64(344.27))
('ORCL', '2025-05-28', np.float64(163.85))
('ORCL', '2025-05-29', np.float64(162.9))
('ORCL', '2025-05-30', np.float64(165.53))
('ORCL', '2025-06-02', np.float64(166.57))
('ORCL', '2025-06-03', np.float64(169.14))
('AMZN', '2025-05-28', np.float64(204.72))
('AMZN', '2025-05-29', np.float64(205.7))
('AMZN', '2025-05-30', np.float64(205.01))
('AMZN', '2025-06-02', np.float64(206.65))
('AMZN', '2025-06-03', np.float64(205.71))


In [ ]:
import mysql.connector
from mysql.connector import errorcode
try:
    cnx = mysql.connector.connect(user='root', password='PASSWORD_DI_GABRI',
                                  host='127.0.0.1',
                                  database='sampledb')
    cursor = cnx.cursor()
    query_add_stocks = ("""INSERT INTO stocks (ticker, date, price) VALUES (%s, %s, %s)""")     # definire la query
    cursor.executemany(query_add_stocks, data)     # aggiungere le righe del prezzo delle azioni
    # executemany: 
    cnx.commit()
except mysql.connector.Error as err:
    print("Error-Code:", err.errno)
    print("Error-Message: {}".format(err.msg))
finally:
    cursor.close()
    cnx.close()

In [ ]:
import pandas as pd
import mysql.connector
from mysql.connector import errorcode

try:
    cnx = mysql.connector.connect(user='root', password='PASSWORD_DI_GABRI',
                                  host='127.0.0.1',
                                  database='sampledb')
    query = ("""SELECT s.* FROM stocks AS s
             LEFT JOIN
             (SELECT DISTINCT(ticker)
                FROM(SELECT price/LAG(price) OVER(PARTITION BY ticker ORDER BY date) AS dif, ticker FROM stocks) AS b
                WHERE dif <0.99) AS a ON a.ticker = s.ticker
            WHERE a.ticker IS NULL""")
    df_stocks = pd.read_sql(query, con=cnx)
    df_stocks = df_stocks.set_index(['ticker','date'])
except mysql.connector.Error as err:
    print("Error-Code:", err.errno)
    print("Error-Message: {}".format(err.msg))
finally:
    cnx.close()
# ricevo un warning: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy. df_stocks = pd.read_sql(query, con=cnx)
# passo un oggetto di connessione mysql.connector.connect(...) direttamente a pd.read_sql().
# Pandas supporta ufficialmente solo connessioni SQLAlchemy (o sqlite3),
# quindi non garantisce il corretto funzionamento con mysql.connector.    
    

C:\Users\gabriele.greco\AppData\Local\Temp\ipykernel_1772\149338559.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_stocks = pd.read_sql(query, con=cnx)


In [ ]:
# pip install sqlalchemy mysql-connector-python
from sqlalchemy import create_engine
import pandas as pd
import urllib.parse

pw = urllib.parse.quote_plus('PASSWORD_DI_GABRI')

engine = create_engine(f"mysql+mysqlconnector://root:{pw}@127.0.0.1/sampledb")

query = """
SELECT s.* FROM stocks AS s
LEFT JOIN (
    SELECT DISTINCT(ticker)
    FROM (
        SELECT price / LAG(price) OVER (PARTITION BY ticker ORDER BY date) AS dif, ticker
        FROM stocks
    ) AS b
    WHERE dif < 0.99
) AS a ON a.ticker = s.ticker
WHERE a.ticker IS NULL
"""

df_stocks = pd.read_sql(query, con=engine)
df_stocks = df_stocks.set_index(['ticker', 'date'])


In [29]:
print(df_stocks)

                    price
ticker date              
ORCL   2025-05-28  163.85
       2025-05-29  162.90
       2025-05-30  165.53
       2025-06-02  166.57
       2025-06-03  169.14
AMZN   2025-05-28  204.72
       2025-05-29  205.70
       2025-05-30  205.01
       2025-06-02  206.65
       2025-06-03  205.71


## Redis

In [33]:
import redis
# `docker run --name redis-stack -d -p 6379:6379 redis/redis-stack-server:latest`

# Connessione a Redis in esecuzione in Docker sulla porta 6379
r = redis.Redis(host='localhost', port=6379, decode_responses=True)

r.set('messaggio', 'ciao dal container!')
print(r.get('messaggio'))

ciao dal container!


In [34]:
r = redis.Redis()
r.mset({"emp1": "Maya Silver", "emp2": "John Jamison"})
r.get("emp1")

b'Maya Silver'

In [33]:
from datetime import timedelta
r.setex("cab26", timedelta(minutes=1), value="in the area now")

True

In [38]:
cabDict = {"ID": "cab48", "Driver": "Dan Varsky", "Brand": "Volvo"}
r.hset("cab48", mapping=cabDict)
r.hgetall("cab48")

{b'ID': b'cab48', b'Driver': b'Dan Varsky', b'Brand': b'Volvo'}

## Mongo

In [ ]:
from pymongo import MongoClient

# Connessione a MongoDB (localhost:27017)
client = MongoClient("mongodb://admin:secret@localhost:27017/")
db = client["miodatabase"] # Accedi a un database (verrà creato se non esiste)
collezione = db["utenti"] # Accedi a una collezione
collezione.insert_one({"nome": "Mario", "email": "mario@example.com"}) # Inserisci un documento
for utente in collezione.find(): # Recupera e stampa tutti i documenti
    print(utente)

{'_id': ObjectId('68402146af5003d7b5d25594'), 'nome': 'Mario', 'email': 'mario@example.com'}


In [44]:
client = MongoClient("mongodb://admin:secret@localhost:27017/")

db = client['sampledb'] # per accedere agli attributi: db = client.sampledb
emps_collection = db['emps']

emp = {"empno": 9001, "empname": "Jeff Russell", "orders": [2608, 2617, 2620]}
result = emps_collection.insert_one(emp)

In [45]:
print(result.inserted_id)

68402237af5003d7b5d2559d


In [ ]:
emp = emps_collection.find_one({"empno": 9001})
print(emp)

# Aggregazione

In [27]:
import pandas as pd

def load_data():
    orders = [(9423517, '2022-02-04', 9001),
              (4626232, '2022-02-04', 9003),
              (9423534, '2022-02-04', 9001),
              (9423679, '2022-02-05', 9002),
              (4626377, '2022-02-05', 9003),
              (4626412, '2022-02-05', 9004),
              (9423783, '2022-02-06', 9002),
              (4626490, '2022-02-06', 9004)]
    
    details = [(9423517, 'Jeans', 'Rip Curl', 87.0, 1),
               (9423517, 'Jacket', 'The North Face', 112.0, 1),
               (4626232, 'Socks', 'Vans', 15.0, 1),
               (4626232, 'Jeans', 'Quiksilver', 82.0, 1),
               (9423534, 'Socks', 'DC', 10.0, 2),
               (9423534, 'Socks', 'Quiksilver', 12.0, 2),
               (9423679, 'T-shirt', 'Patagonia', 35.0, 1),
               (4626377, 'Hoody', 'Animal', 44.0, 1),
               (4626377, 'Cargo Shorts', 'Animal', 38.0, 1),
               (4626412, 'Shirt', 'Volcom', 78.0, 1),
               (9423783, 'Boxer Shorts', 'Superdry', 30.0, 2),
               (9423783, 'Shorts', 'Globe', 26.0, 1),
               (4626490, 'Cargo Shorts', 'Billabong', 54.0, 1),
               (4626490, 'Sweater', 'Dickies', 56.0, 1)]

    df_details = pd.DataFrame(details, columns =['OrderNo', 'Item', 'Brand', 'Price', 'Quantity'])
    df_orders = pd.DataFrame(orders, columns =['OrderNo', 'Date', 'Empno'])
    
    emps = [(9001, 'Jeff Russell', 'LA'),
            (9002, 'Jane Boorman', 'San Francisco'),
            (9003, 'Tom Heints', 'NYC'),
            (9004, 'Maya Silver', 'Philadelphia')]
    df_emps = pd.DataFrame(emps, columns =['Empno', 'Empname', 'Location'])
    
    locations = [('LA', 'West'),
                 ('San Francisco', 'West'),
                 ('NYC', 'East'),
                 ('Philadelphia', 'East')]
    df_locations = pd.DataFrame(locations, columns =['Location', 'Region'])
    return df_orders, df_details, df_emps, df_locations

def combination(df_orders, df_details, df_emps, df_locations):
    df_sales = df_orders.merge(df_details)
    return df_sales

In [7]:
df_orders, df_details, df_emps, df_locations = load_data()
print("Dati caricati\n")
df_sales = combination(df_orders, df_details, df_emps, df_locations)
print(df_sales)
df_sales['Total'] = df_sales['Price'] * df_sales['Quantity']

Dati caricati

    OrderNo        Date  Empno          Item           Brand  Price  Quantity
0   9423517  2022-02-04   9001         Jeans        Rip Curl   87.0         1
1   9423517  2022-02-04   9001        Jacket  The North Face  112.0         1
2   4626232  2022-02-04   9003         Socks            Vans   15.0         1
3   4626232  2022-02-04   9003         Jeans      Quiksilver   82.0         1
4   9423534  2022-02-04   9001         Socks              DC   10.0         2
5   9423534  2022-02-04   9001         Socks      Quiksilver   12.0         2
6   9423679  2022-02-05   9002       T-shirt       Patagonia   35.0         1
7   4626377  2022-02-05   9003         Hoody          Animal   44.0         1
8   4626377  2022-02-05   9003  Cargo Shorts          Animal   38.0         1
9   4626412  2022-02-05   9004         Shirt          Volcom   78.0         1
10  9423783  2022-02-06   9002  Boxer Shorts        Superdry   30.0         2
11  9423783  2022-02-06   9002        Shorts     

In [ ]:
# Per filtrare il DataFrame fino alle colonne necessarie, occorre passare una lista dei nomi delle colonne all’operatore [] del DataFrame, come mostrato qui:
df_sales = df_sales[['Date','Empno','Total']]

df_sales_emps = df_sales.merge(df_emps)
df_result = df_sales_emps.merge(df_locations)
print(df_result)

df_result = df_result[['Date','Region','Total']]
print(df_result)

df_date_region = df_result.groupby(['Date','Region']).sum()
print(df_date_region)

          Date  Empno  Total       Empname       Location Region
0   2022-02-04   9001   87.0  Jeff Russell             LA   West
1   2022-02-04   9001  112.0  Jeff Russell             LA   West
2   2022-02-04   9003   15.0    Tom Heints            NYC   East
3   2022-02-04   9003   82.0    Tom Heints            NYC   East
4   2022-02-04   9001   20.0  Jeff Russell             LA   West
5   2022-02-04   9001   24.0  Jeff Russell             LA   West
6   2022-02-05   9002   35.0  Jane Boorman  San Francisco   West
7   2022-02-05   9003   44.0    Tom Heints            NYC   East
8   2022-02-05   9003   38.0    Tom Heints            NYC   East
9   2022-02-05   9004   78.0   Maya Silver   Philadelphia   East
10  2022-02-06   9002   60.0  Jane Boorman  San Francisco   West
11  2022-02-06   9002   26.0  Jane Boorman  San Francisco   West
12  2022-02-06   9004   54.0   Maya Silver   Philadelphia   East
13  2022-02-06   9004   56.0   Maya Silver   Philadelphia   East
          Date Region  To

In [9]:
print(df_date_region.index) # per vedere come lavora il multiindex

print(df_date_region[df_date_region.index.isin( [('2022-02-05', 'West')])])
print(df_date_region[df_date_region.index.isin([('2022-02-05', 'East'), ('2022-02-05', 'West')])])
print(df_date_region[df_date_region.index.isin([('2022-02-06', 'East'),('2022-02-04', 'East'), ('2022-02-05', 'West')])])

MultiIndex([('2022-02-04', 'East'),
            ('2022-02-04', 'West'),
            ('2022-02-05', 'East'),
            ('2022-02-05', 'West'),
            ('2022-02-06', 'East'),
            ('2022-02-06', 'West')],
           names=['Date', 'Region'])
                   Total
Date       Region       
2022-02-05 West     35.0
                   Total
Date       Region       
2022-02-05 East    160.0
           West     35.0
                   Total
Date       Region       
2022-02-04 East     97.0
2022-02-05 West     35.0
2022-02-06 East    110.0


In [ ]:
# SLICING di aggregation
print(df_date_region[('2022-02-04', 'East'):('2022-02-05', 'West')])

print(df_date_region['2022-02-04':'2022-02-05'])
# qui si utilizza lo slice due volte
print(df_date_region.loc[(slice('2022-02-05', '2022-02-06'), slice(None)), :])

                   Total
Date       Region       
2022-02-04 East     97.0
           West    243.0
2022-02-05 East    160.0
           West     35.0
                   Total
Date       Region       
2022-02-04 East     97.0
           West    243.0
2022-02-05 East    160.0
           West     35.0
                   Total
Date       Region       
2022-02-05 East    160.0
           West     35.0
2022-02-06 East    110.0
           West     86.0


In [ ]:
df_date_region.loc[(slice('2022-02-05', '2022-02-06'), slice('East')), :]
# possiamo specificare anche un intervallo region

Total
Date       Region       
2022-02-05 East    160.0
2022-02-06 East    110.0

In [20]:
# Aggiungere un totale generale
ps = df_date_region.sum(axis = 0)
print(ps) # sum restituisce una series pandas con la somma sulal colonna total
ps.name=('All','All')
        # il primo all si riferisce alla componente date delal chiave mentre il secondo alla Region
# df_date_region_total = df_date_region.append(ps)
df_date_region_total = pd.concat([df_date_region, ps.to_frame().T])
print(df_date_region_total)
print(df_date_region_total[df_date_region_total.index.isin([('All', 'All')])])

Total    731.0
dtype: float64
                 Total
2022-02-04 East   97.0
           West  243.0
2022-02-05 East  160.0
           West   35.0
2022-02-06 East  110.0
           West   86.0
All        All   731.0
         Total
All All  731.0


In [ ]:
# aggiungere totali parziali
df_totals = []

for date, date_df in df_date_region.groupby(level=0):
    df_totals.append(date_df)  # aggiunge le righe esistenti
    ps = date_df.sum(axis=0)
    ps.name = (date, 'All')  # MultiIndex (data, 'All')
    df_totals.append(ps.to_frame().T)  # aggiunge la riga di somma

# Unisce tutto in un unico DataFrame
df_totals = pd.concat(df_totals)
print(df_totals)

                 Total
2022-02-04 East   97.0
           West  243.0
           All   340.0
2022-02-05 East  160.0
           West   35.0
           All   195.0
2022-02-06 East  110.0
           West   86.0
           All   196.0


In [26]:
df_totals = pd.concat([df_totals, df_date_region_total.loc[[('All', 'All')]]])
df_totals

Total
2022-02-04 East   97.0
           West  243.0
           All   340.0
2022-02-05 East  160.0
           West   35.0
           All   195.0
2022-02-06 East  110.0
           West   86.0
           All   196.0
All        All   731.0
           All   731.0

In [32]:
# RIGHE APPARTENENTI AD UN GRUPPO
group = df_result.groupby(['Date','Region'])
group.get_group(('2022-02-04','West'))

Date Region  Total
0  2022-02-04   West   87.0
1  2022-02-04   West  112.0
4  2022-02-04   West   20.0
5  2022-02-04   West   24.0

## Combinare i dataset

In [35]:
orders_2022_02_04 = [
    (9423517, '2022-02-04', 9001),
    (4626232, '2022-02-04', 9002),
    (9423534, '2022-02-04', 9001)]
orders_2022_02_05 = [
    (9423679, '2022-02-05', 9002),
    (4626377, '2022-02-05', 9003),
    (4626412, '2022-02-05', 9004)]
orders_2022_02_06 = [
    (9423783, '2022-02-06', 9002),
    (4626490, '2022-02-06', 9004)]
orders = orders_2022_02_04 + orders_2022_02_05 + orders_2022_02_06
print(orders)

[(9423517, '2022-02-04', 9001), (4626232, '2022-02-04', 9002), (9423534, '2022-02-04', 9001), (9423679, '2022-02-05', 9002), (4626377, '2022-02-05', 9003), (4626412, '2022-02-05', 9004), (9423783, '2022-02-06', 9002), (4626490, '2022-02-06', 9004)]


In [36]:
# l'operatore ** scompone un dizionario nelle sue singole coppie chiave valore
extra_fields_9423517 = {'ShippingInstructions' :
    { 'name' : 'John Silver',
     'Phone' : [{ 'type' : 'Office', 'number' : '809-123-9309' },
                { 'type' : 'Mobile', 'number' : '417-123-4567' }
                ]}
    }
order_9423517 = {'OrderNo':9423517, 'Date':'2022-02-04', 'Empno':9001}
order_9423517 = {**order_9423517, **extra_fields_9423517}
print(order_9423517)

{'OrderNo': 9423517, 'Date': '2022-02-04', 'Empno': 9001, 'ShippingInstructions': {'name': 'John Silver', 'Phone': [{'type': 'Office', 'number': '809-123-9309'}, {'type': 'Mobile', 'number': '417-123-4567'}]}}


In [39]:
details = [
    (9423517, 'Jeans', 'Rip Curl', 87.0, 1),
    (9423517, 'Jacket', 'The North Face', 112.0, 1),
    (4626232, 'Socks', 'Vans', 15.0, 1),
    (4626232, 'Jans', 'Quicksilver', 82.0, 1),
    (9423534, 'Socks', 'DC', 10.0, 2),
    (9423534, 'Socks', 'Quicksilver', 12.0, 2),
    (9423679, 'T-shirt', 'Patagonia', 35.0, 1),
    (4626377, 'Hoody', 'Animal', 44.0, 1),
    (4626377, 'Cargo Shorts', 'Animal', 38.0, 1),
    (4626412, 'Shirt', 'Volcom', 78.0, 1),
    (9423783, 'Boxer Shorts', 'Superdry', 30.0, 2),
    (9423783, 'Shorts', 'Globe', 26.0, 1),
    (4626490, 'Cargo Shorts', 'Billabong', 54.0, 1),
    (4626490, 'Sweater', 'Dickies', 56.0, 1),
]
orders_details = []
for o in orders:
    for d in details:
        if d[0] == o[0]:
            orders_details.append(o + d[1:]) # slicing per la tupla details
# più pythonica
orders_details = []
orders_details = [[o for o in orders if d[0] == o[0]][0] + d[1:] for d in details]
for o in orders_details:
    print(o)
print(orders_details)

(9423517, '2022-02-04', 9001, 'Jeans', 'Rip Curl', 87.0, 1)
(9423517, '2022-02-04', 9001, 'Jacket', 'The North Face', 112.0, 1)
(4626232, '2022-02-04', 9002, 'Socks', 'Vans', 15.0, 1)
(4626232, '2022-02-04', 9002, 'Jans', 'Quicksilver', 82.0, 1)
(9423534, '2022-02-04', 9001, 'Socks', 'DC', 10.0, 2)
(9423534, '2022-02-04', 9001, 'Socks', 'Quicksilver', 12.0, 2)
(9423679, '2022-02-05', 9002, 'T-shirt', 'Patagonia', 35.0, 1)
(4626377, '2022-02-05', 9003, 'Hoody', 'Animal', 44.0, 1)
(4626377, '2022-02-05', 9003, 'Cargo Shorts', 'Animal', 38.0, 1)
(4626412, '2022-02-05', 9004, 'Shirt', 'Volcom', 78.0, 1)
(9423783, '2022-02-06', 9002, 'Boxer Shorts', 'Superdry', 30.0, 2)
(9423783, '2022-02-06', 9002, 'Shorts', 'Globe', 26.0, 1)
(4626490, '2022-02-06', 9004, 'Cargo Shorts', 'Billabong', 54.0, 1)
(4626490, '2022-02-06', 9004, 'Sweater', 'Dickies', 56.0, 1)
[(9423517, '2022-02-04', 9001, 'Jeans', 'Rip Curl', 87.0, 1), (9423517, '2022-02-04', 9001, 'Jacket', 'The North Face', 112.0, 1), (4626232

In [40]:
# diversi tipi di join per le liste
# la lista details potrebbe contenere righe d’ordine per ordini non presenti nella lista orders.
details.append((4626592, 'Shorts', 'Protest', 48.0, 1))
orders_details = [[o for o in orders if d[0] == o][0] + d[1:] for d in details]

IndexError: list index out of range

In [ ]:
orders_details = [[o for o in orders if d[0] in o][0] + d[1:] for d in details if d[0] in [o[0] for o in orders]]
# Il problema viene eliminato escludendo tutte le righe details che non hanno una riga
# corrispondente nella lista orders e implementando il controllo nella clausola if che
# segue il ciclo for d in details.

# per fare un right join
# una right join restituisce tutte le righe del dataset destro e solo le righe corrispondenti del dataset sinistro
orders_details_right = [[o for o in orders if d[0] in o][0] + d[1:] if d[0] in [o[0] for o in orders] else (d[0], None, None) + d[1:] for d in details]
for o in orders_details_right:
    print(o)

(9423517, '2022-02-04', 9001, 'Jeans', 'Rip Curl', 87.0, 1)
(9423517, '2022-02-04', 9001, 'Jacket', 'The North Face', 112.0, 1)
(4626232, '2022-02-04', 9002, 'Socks', 'Vans', 15.0, 1)
(4626232, '2022-02-04', 9002, 'Jans', 'Quicksilver', 82.0, 1)
(9423534, '2022-02-04', 9001, 'Socks', 'DC', 10.0, 2)
(9423534, '2022-02-04', 9001, 'Socks', 'Quicksilver', 12.0, 2)
(9423679, '2022-02-05', 9002, 'T-shirt', 'Patagonia', 35.0, 1)
(4626377, '2022-02-05', 9003, 'Hoody', 'Animal', 44.0, 1)
(4626377, '2022-02-05', 9003, 'Cargo Shorts', 'Animal', 38.0, 1)
(4626412, '2022-02-05', 9004, 'Shirt', 'Volcom', 78.0, 1)
(9423783, '2022-02-06', 9002, 'Boxer Shorts', 'Superdry', 30.0, 2)
(9423783, '2022-02-06', 9002, 'Shorts', 'Globe', 26.0, 1)
(4626490, '2022-02-06', 9004, 'Cargo Shorts', 'Billabong', 54.0, 1)
(4626490, '2022-02-06', 9004, 'Sweater', 'Dickies', 56.0, 1)
(4626592, None, None, 'Shorts', 'Protest', 48.0, 1)


In [45]:
s = sum(pr*qt for _, _, _, _, _, pr, qt in orders_details_right)
print(s)
s = sum(pr*qt for _, dt, _, _, _, pr, qt in orders_details_right if dt != None)
print(s)

779.0
731.0


In [ ]:
# CONCATENARE ARRAY NUMPY
import numpy as np
jeff_salary = [2700, 3000, 3000]
nick_salary = [2600, 2800, 2800]
tom_salary = [2300, 2500, 2500]
base_salary1 = np.array([jeff_salary, nick_salary, tom_salary])

maya_salary = [2200, 2400, 2400]
john_salary = [2500, 2700, 2700]
base_salary2 = np.array([maya_salary, john_salary])

base_salary = np.concatenate((base_salary1, base_salary2), axis=0)
print(base_salary)

[[2700 3000 3000]
 [2600 2800 2800]
 [2300 2500 2500]
 [2200 2400 2400]
 [2500 2700 2700]]


In [47]:
new_month_salary = np.array([[3000],[2900],[2500],[2500],[2700]])
base_salary = np.concatenate((base_salary, new_month_salary), axis=1)
print(base_salary)

[[2700 3000 3000 3000]
 [2600 2800 2800 2900]
 [2300 2500 2500 2500]
 [2200 2400 2400 2500]
 [2500 2700 2700 2700]]


In [61]:
# Concatenere dataframe
import pandas as pd
salary_df1 = pd.DataFrame({
    'jeff': jeff_salary,
    'nick': nick_salary,
    'tom': tom_salary
})
salary_df1.index = ['June', 'July', 'August']
print(salary_df1)
salary_df1 = salary_df1.T # Traspose
print(salary_df1)


        jeff  nick   tom
June    2700  2600  2300
July    3000  2800  2500
August  3000  2800  2500
      June  July  August
jeff  2700  3000    3000
nick  2600  2800    2800
tom   2300  2500    2500


In [62]:
salary_df2 = pd.DataFrame({
    'maya': maya_salary,
    'john': john_salary},
    index = ['June', 'July', 'August']).T

In [67]:
salary_df = pd.concat([salary_df1, salary_df2])
print(salary_df)

      June  July  August
jeff  2700  3000    3000
nick  2600  2800    2800
tom   2300  2500    2500
maya  2200  2400    2400
john  2500  2700    2700


In [68]:
salary_df3 = pd.DataFrame({
    'September': [3000,2800,2500,2400,2700],
    'October': [3200,3000,2700,2500,2900]},
    index = ['jeff', 'nick', 'tom', 'maya', 'john'])

In [69]:
salary_df = pd.concat([salary_df, salary_df3], axis=1)
print(salary_df)  # con axis 1 facciamo il concat orizzontale

      June  July  August  September  October
jeff  2700  3000    3000       3000     3200
nick  2600  2800    2800       2800     3000
tom   2300  2500    2500       2500     2700
maya  2200  2400    2400       2400     2500
john  2500  2700    2700       2700     2900


In [70]:
salary_df = salary_df.drop(['September', 'October'], axis=1)
print(salary_df)

      June  July  August
jeff  2700  3000    3000
nick  2600  2800    2800
tom   2300  2500    2500
maya  2200  2400    2400
john  2500  2700    2700


In [71]:
salary_df = salary_df.drop(['nick', 'maya'], axis=0)
print(salary_df)

      June  July  August
jeff  2700  3000    3000
tom   2300  2500    2500
john  2500  2700    2700


In [73]:
# Concatenere dataframe multiindex
df_date_region1 = pd.DataFrame([
    ('2022-02-04', 'East', 97.0),
    ('2022-02-04', 'West', 243.0),
    ('2022-02-05', 'East', 160.0),
    ('2022-02-05', 'West', 35.0),
    ('2022-02-06', 'East', 110.0),
    ('2022-02-06', 'West', 86.0)],
    columns = ['Date', 'Region', 'Total']).set_index(['Date', 'Region'])

df_date_region2 = pd.DataFrame([
    ('2022-02-04', 'South', 114.0),
    ('2022-02-05', 'South', 325.0),
    ('2022-02-06', 'South', 212.0)],
    columns=['Date', 'Region', 'Total']).set_index(['Date', 'Region'])

df_date_region = pd.concat([df_date_region1, df_date_region2]).sort_index(level=['Date','Region'])
print(df_date_region)

                   Total
Date       Region       
2022-02-04 East     97.0
           South   114.0
           West    243.0
2022-02-05 East    160.0
           South   325.0
           West     35.0
2022-02-06 East    110.0
           South   212.0
           West     86.0


In [76]:
import pandas as pd
df_orders = pd.DataFrame(orders, columns =['OrderNo', 'Date', 'Empno'])
df_details = pd.DataFrame(details, columns =['OrderNo', 'Item', 'Brand','Price', 'Quantity'])

new_row = pd.DataFrame([{
    'OrderNo': 4626592,
    'Item': 'Shorts',
    'Brand': 'Protest',
    'Price': 48.0,
    'Quantity': 1
}])

df_details = pd.concat([df_details, new_row], ignore_index=True)
df_orders_details_right = df_orders.merge(df_details, how='right',left_on='OrderNo', right_on='OrderNo')
print(df_orders_details_right)

    OrderNo        Date   Empno          Item           Brand  Price  Quantity
0   9423517  2022-02-04  9001.0         Jeans        Rip Curl   87.0         1
1   9423517  2022-02-04  9001.0        Jacket  The North Face  112.0         1
2   4626232  2022-02-04  9002.0         Socks            Vans   15.0         1
3   4626232  2022-02-04  9002.0          Jans     Quicksilver   82.0         1
4   9423534  2022-02-04  9001.0         Socks              DC   10.0         2
5   9423534  2022-02-04  9001.0         Socks     Quicksilver   12.0         2
6   9423679  2022-02-05  9002.0       T-shirt       Patagonia   35.0         1
7   4626377  2022-02-05  9003.0         Hoody          Animal   44.0         1
8   4626377  2022-02-05  9003.0  Cargo Shorts          Animal   38.0         1
9   4626412  2022-02-05  9004.0         Shirt          Volcom   78.0         1
10  9423783  2022-02-06  9002.0  Boxer Shorts        Superdry   30.0         2
11  9423783  2022-02-06  9002.0        Shorts       

In [77]:
print(df_orders_details_right.dtypes)


OrderNo       int64
Date         object
Empno       float64
Item         object
Brand        object
Price       float64
Quantity      int64
dtype: object


In [80]:
df_orders_details_right = df_orders_details_right.fillna({'Empno':0}).astype({'Empno':'int64'})
print(df_orders_details_right)

    OrderNo        Date  Empno          Item           Brand  Price  Quantity
0   9423517  2022-02-04   9001         Jeans        Rip Curl   87.0         1
1   9423517  2022-02-04   9001        Jacket  The North Face  112.0         1
2   4626232  2022-02-04   9002         Socks            Vans   15.0         1
3   4626232  2022-02-04   9002          Jans     Quicksilver   82.0         1
4   9423534  2022-02-04   9001         Socks              DC   10.0         2
5   9423534  2022-02-04   9001         Socks     Quicksilver   12.0         2
6   9423679  2022-02-05   9002       T-shirt       Patagonia   35.0         1
7   4626377  2022-02-05   9003         Hoody          Animal   44.0         1
8   4626377  2022-02-05   9003  Cargo Shorts          Animal   38.0         1
9   4626412  2022-02-05   9004         Shirt          Volcom   78.0         1
10  9423783  2022-02-06   9002  Boxer Shorts        Superdry   30.0         2
11  9423783  2022-02-06   9002        Shorts           Globe   2

In [ ]:
# join molti a molti
import pandas as pd
books = pd.DataFrame({'book_id': ['b1', 'b2', 'b3'],
                      'title': ['Beautiful Coding', 'Python for Web Development', 'Pythonic Thinking'],
                      'topic': ['programming', 'Python, Web', 'Python']})
authors = pd.DataFrame({'author_id': ['jsn', 'tri', 'wsn'],
                        'author': ['Johnson', 'Treloni', 'Willson']})

matching = pd.DataFrame({'author_id': ['jsn', 'jsn','tri', 'wsn'],'book_id': ['b1', 'b2', 'b2', 'b3']})
print(matching)

authorship = books.merge(matching).merge(authors)[['title','topic','author']]
print(authorship)

  author_id book_id
0       jsn      b1
1       jsn      b2
2       tri      b2
3       wsn      b3


# Esercizi

In [ ]:
# Esercizio #8: Eseguire una join uno-a-molti
# Modificate il codice mostrato nella sezione precedente in modo che la query sia una join
# della tabella emps con la tabella orders. È possibile mantenere la condizione che empno sia
# maggiore di 9001. Adattate la chiamata print() per produrre le righe della join modificata.

try:  
    cnx = mysql.connector.connect(user='root', password='PASSWORD_DI_GABRI',
                                  host='127.0.0.1',
                                  database='sampledb')
    cursor = cnx.cursor()
    query = ("""SELECT e.empno, e.empname, e.job, o.total FROM emps AS e JOIN orders AS o ON e.empno = o.empno WHERE e.empno > %s""")
    empno = 9001
    cursor.execute(query, (empno,))
    for (empno, empname, job, total) in cursor:
        print("{}, {}, {}, {}".format(empno, empname, job, total))
except mysql.connector.Error as err:
    print("Error-Code:", err.errno)
    print("Error-Message: {}".format(err.msg))
finally:
    cursor.close()
    cnx.close()


9002, Jane Boorman, sales, 95
9002, Jane Boorman, sales, 218


In [56]:
# Esercizio 9: Inserire e interrogare più documenti
# Continuando con l’insieme emps creato nel database sampledb, provate a eseguire
# inserti massivi con il metodo insert_many() e interrogate più di un documento con il metodo find()

# link insert_many(): https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.insert_many
# link find(): https://pymongo.readthedocs.io/en/stable/api/pymongo/collection.html#pymongo.collection.Collection.find

from pymongo import MongoClient

client = MongoClient("mongodb://admin:secret@localhost:27017/")
db = client['sampledb'] # per accedere agli attributi: db = client.sampledb
emps_collection = db['emps']
# emp = {"empno": 9001, "empname": "Jeff Russell", "orders": [2608, 2617, 2620]}
# result = emps_collection.insert_one(emp)

employees = [
    {"empno": 9002, "empname": "Alice Smith", "orders": [2609, 2618]},
    {"empno": 9003, "empname": "Bob Johnson", "orders": [2610]},
    {"empno": 9004, "empname": "Charlie Brown", "orders": [2611, 2621, 2630]}
]
result_insert = emps_collection.insert_many(employees)
print(f"Documenti inseriti, id: {result_insert.inserted_ids}")

# emp = emps_collection.find_one({"empno": 9001})
# print(emp)

print("Documenti trovati:")
for emp in emps_collection.find():
    print(emp)

Documenti inseriti, id: [ObjectId('68403adfaf5003d7b5d255ba'), ObjectId('68403adfaf5003d7b5d255bb'), ObjectId('68403adfaf5003d7b5d255bc')]
Documenti trovati:
{'_id': ObjectId('6840220baf5003d7b5d25599'), 'empno': 9001, 'empname': 'Jeff Russell', 'orders': [2608, 2617, 2620]}
{'_id': ObjectId('684024edaf5003d7b5d255a2'), 'empno': 9002, 'empname': 'Alice Smith', 'orders': [2609, 2618]}
{'_id': ObjectId('684024edaf5003d7b5d255a3'), 'empno': 9003, 'empname': 'Bob Johnson', 'orders': [2610]}
{'_id': ObjectId('684024edaf5003d7b5d255a4'), 'empno': 9004, 'empname': 'Charlie Brown', 'orders': [2611, 2621, 2630]}
{'_id': ObjectId('68403addaf5003d7b5d255b2'), 'empno': 9002, 'empname': 'Alice Smith', 'orders': [2609, 2618]}
{'_id': ObjectId('68403addaf5003d7b5d255b3'), 'empno': 9003, 'empname': 'Bob Johnson', 'orders': [2610]}
{'_id': ObjectId('68403addaf5003d7b5d255b4'), 'empno': 9004, 'empname': 'Charlie Brown', 'orders': [2611, 2621, 2630]}
{'_id': ObjectId('68403adfaf5003d7b5d255b6'), 'empno':

In [57]:
client = MongoClient("mongodb://admin:secret@localhost:27017/")
db = client['sampledb']
emps_collection = db['emps']
# 1. Trova tutti i documenti ordinati per empno e _id (così tieni il primo inserito)
all_docs = emps_collection.find().sort([("empno", 1), ("_id", 1)])
seen_empnos = set()
to_delete_ids = []
# 2. Identifica i duplicati
for doc in all_docs:
    empno = doc["empno"]
    if empno in seen_empnos:
        to_delete_ids.append(doc["_id"])
    else:
        seen_empnos.add(empno)

# 3. Rimuovi i documenti duplicati
if to_delete_ids:
    result = emps_collection.delete_many({"_id": {"$in": to_delete_ids}})
    print(f"{result.deleted_count} documenti duplicati rimossi.")
else:
    print("Nessun duplicato trovato.")


9 documenti duplicati rimossi.


In [ ]:
# Esercizio 10 La presenza di righe per i totali in un DataFrame consente di utilizzarlo come report senza 
# dover aggiungere ulteriori passaggi. Tuttavia, se si intende utilizzare il DataFrame in ulteriori
# operazioni di aggregazione, potrebbe essere necessario escludere le righe per i totali.
#  Provate a filtrare il DataFrame df_totals creato nella sezione precedente, escludendo le 
# righe del totale generale e del subtotale. Utilizzate le tecniche di slicing discusse in questo capitolo.

df_orders, df_details, df_emps, df_locations = load_data()
df_sales = combination(df_orders, df_details, df_emps, df_locations)
df_sales['Total'] = df_sales['Price'] * df_sales['Quantity']
df_sales = df_sales[['Date','Empno','Total']] # Per filtrare il DataFrame fino alle colonne necessarie, occorre passare una lista dei nomi delle colonne all’operatore [] del DataFrame, come mostrato qui:

df_sales_emps = df_sales.merge(df_emps)
df_result = df_sales_emps.merge(df_locations)
df_result = df_result[['Date','Region','Total']]
df_date_region = df_result.groupby(['Date','Region']).sum()

ps = df_date_region.sum(axis = 0)   # Aggiungere un totale generale
print(ps)                           # sum restituisce una series pandas con la somma sulal colonna total
ps.name=('All','All')               # il primo all si riferisce alla componente date delal chiave mentre il secondo alla Region

df_date_region_total = pd.concat([df_date_region, ps.to_frame().T])
print(df_date_region_total)
print(df_date_region_total[df_date_region_total.index.isin([('All', 'All')])])

# aggiungere totali parziali
df_totals = []

for date, date_df in df_date_region.groupby(level=0):
    df_totals.append(date_df)  # aggiunge le righe esistenti
    ps = date_df.sum(axis=0)
    ps.name = (date, 'All')  # MultiIndex (data, 'All')
    df_totals.append(ps.to_frame().T)  # aggiunge la riga di somma

# Unisce tutto in un unico DataFrame
df_totals = pd.concat(df_totals)
print(df_totals)

# SOLUZIONE in esercizio10.py


Total    731.0
dtype: float64
                 Total
2022-02-04 East   97.0
           West  243.0
2022-02-05 East  160.0
           West   35.0
2022-02-06 East  110.0
           West   86.0
All        All   731.0
         Total
All All  731.0
                 Total
2022-02-04 East   97.0
           West  243.0
           All   340.0
2022-02-05 East  160.0
           West   35.0
           All   195.0
2022-02-06 East  110.0
           West   86.0
           All   196.0


In [ ]:
# Esercizio 11: Aggiungere righe/colonne nuove a un array Numpy. Continuando con l’esempio precedente,
# create un nuovo array NumPy a due colonne con le # informazioni sullo stipendio di altri due mesi per ciascun dipendente.
# Quindi, concatenate l’array esistente base_salary con l’array appena creato. Allo stesso modo, aggiungete una
# nuova riga all’array base_salary, aggiungendo così le informazioni sullo stipendio di un altro dipendente.
# Notate che quando si aggiunge una singola riga o colonna a un array NumPy, è
# possibile utilizzare la funzione numpy.append() piuttosto che numpy.concatenate().

# CONCATENARE ARRAY NUMPY
import numpy as np
jeff_salary = [2700, 3000, 3000]
nick_salary = [2600, 2800, 2800]
tom_salary = [2300, 2500, 2500]
base_salary1 = np.array([jeff_salary, nick_salary, tom_salary])

maya_salary = [2200, 2400, 2400]
john_salary = [2500, 2700, 2700]
base_salary2 = np.array([maya_salary, john_salary])

base_salary = np.concatenate((base_salary1, base_salary2), axis=0)
print(base_salary)
new_month_salary = np.array([[3000],[2900],[2500],[2500],[2700]])
base_salary = np.concatenate((base_salary, new_month_salary), axis=1)
print(base_salary)

# implementato in module_07/esercizio11.py