# Codice Modulo

In [1]:
import numpy as np

In [2]:
jeff_salary = [2700,3000,3000]
nick_salary = [2600,2800,2800]
tom_salary = [2300,2500,2500]
base_salary = np.array([jeff_salary, nick_salary, tom_salary])
print(base_salary)

[[2700 3000 3000]
 [2600 2800 2800]
 [2300 2500 2500]]


In [3]:
jeff_bonus = [500,400,400]
nick_bonus = [600,300,400]
tom_bonus = [200,500,400]
bonus = np.array([jeff_bonus, nick_bonus, tom_bonus])

In [4]:
salary_bonus = base_salary + bonus
print(type(salary_bonus))
print(salary_bonus)

<class 'numpy.ndarray'>
[[3200 3400 3400]
 [3200 3100 3200]
 [2500 3000 2900]]


In [5]:
print(salary_bonus.max())

3400


In [6]:
print(np.amax(salary_bonus, axis = 1))

[3400 3200 3000]


In [7]:
print(np.amax(salary_bonus, axis = 0))

[3200 3400 3400]


In [27]:
import pandas as pd
data = ['Jeff Russell','Jane Boorman','Tom Heints']
emps_names = pd.Series(data)
print(emps_names)

0    Jeff Russell
1    Jane Boorman
2      Tom Heints
dtype: object


In [28]:
# serie con indici definiti dall'utente
data = ['Jeff Russell','Jane Boorman','Tom Heints']
emps_names = pd.Series(data,index=[9001,9002,9003])
print(emps_names)

9001    Jeff Russell
9002    Jane Boorman
9003      Tom Heints
dtype: object


In [36]:
print(emps_names[9001])
print(emps_names.loc[9001])
print(emps_names.iloc[0])
print(emps_names.loc[9001:9003])
print(emps_names.iloc[0:2])

Jeff Russell
Jeff Russell
Jeff Russell
9001    Jeff Russell
9002    Jane Boorman
9003      Tom Heints
dtype: object
9001    Jeff Russell
9002    Jane Boorman
dtype: object


In [37]:
data = ['jeff.russell','jane.boorman','tom.heints']
emps_emails = pd.Series(data,index=[9001,9002,9003], name = 'emails')
emps_names.name = 'names'
df = pd.concat([emps_names,emps_emails], axis=1)
print(df)

             names        emails
9001  Jeff Russell  jeff.russell
9002  Jane Boorman  jane.boorman
9003    Tom Heints    tom.heints


In [ ]:
import yfinance as yf
tkr = yf.Ticker('TSLA')
hist = tkr.history(period="5d")
hist = hist.drop("Dividends", axis = 1)
hist = hist.drop("Stock Splits", axis = 1)
hist = hist.reset_index()
print(hist)
hist = hist.set_index('Date')
print(hist)

In [48]:
import json
import pandas as pd
from io import StringIO

data = [
{"Empno":9001,"Salary":3000},
{"Empno":9002,"Salary":2800},
{"Empno":9003,"Salary":2500}
]
json_data = json.dumps(data)
# salary = pd.read_json(json_data)
salary = pd.read_json(StringIO((json_data)))
salary = salary.set_index('Empno')
print(salary)

       Salary
Empno        
9001     3000
9002     2800
9003     2500


In [52]:
import pandas as pd
data = [['9001','Jeff Russell', 'sales'],
['9002','Jane Boorman', 'sales'],
['9003','Tom Heints', 'sales']]
emps = pd.DataFrame(data, columns = ['Empno', 'Name', 'Job'])
column_types = {'Empno': int, 'Name': str, 'Job': str}
emps = emps.astype(column_types)
emps = emps.set_index('Empno')
print(emps)

               Name    Job
Empno                     
9001   Jeff Russell  sales
9002   Jane Boorman  sales
9003     Tom Heints  sales


In [50]:
emps_salary = emps.join(salary)
print(emps_salary)

               Name    Job  Salary
Empno                             
9001   Jeff Russell  sales    3000
9002   Jane Boorman  sales    2800
9003     Tom Heints  sales    2500


In [ ]:
new_emp = pd.Series({'Name': 'John Hardy', 'Job': 'sales'}, name = 9004)
emps = emps.append(new_emp)
print(emps)

In [55]:
import pandas as pd
data = [[2608, 9001,35], [2617, 9001,35], [2620, 9001,139], [2621, 9002,95], [2626, 9002,218]]
orders = pd.DataFrame(data, columns = ['Pono', 'Empno', 'Total'])
print(orders)

   Pono  Empno  Total
0  2608   9001     35
1  2617   9001     35
2  2620   9001    139
3  2621   9002     95
4  2626   9002    218


In [56]:
# esempio 1 a N
emps_orders = emps.merge(orders, how='inner', left_on='Empno', right_on='Empno').set_index('Pono')
print(emps_orders)

      Empno          Name    Job  Total
Pono                                   
2608   9001  Jeff Russell  sales     35
2617   9001  Jeff Russell  sales     35
2620   9001  Jeff Russell  sales    139
2621   9002  Jane Boorman  sales     95
2626   9002  Jane Boorman  sales    218


In [57]:
print(orders.groupby(['Empno'])['Total'].mean())

Empno
9001     69.666667
9002    156.500000
Name: Total, dtype: float64


In [58]:
print(orders.groupby(['Empno'])['Total'].sum())

Empno
9001    209
9002    313
Name: Total, dtype: int64


In [ ]:
import pandas as pd
path = 'dataset/sentiment_labelled_sentences/amazon_cells_labelled.txt'
df_sentiment = pd.read_csv(path, names=[ 'review', 'sentiment'], sep='\t')
# Poiché dei tabulatori separano le recensioni dai punteggi di sentiment corrispondenti nel file originale, è necessario specificare \t come separatore .

In [63]:
df_sentiment.head(5)

review  sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [ ]:
from sklearn.model_selection import train_test_split
reviews = df['review'].values
sentiments = df['sentiment'].values
reviews_train, reviews_test, sentiment_train, sentiment_test = train_test_split(reviews, sentiments, test_size=0.2, random_state=500)
# definisce la dimensione del dataset di test, e il random_state per la casualità

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
vectorizer.fit(reviews)
X_train = vectorizer.transform(reviews_train)
X_test = vectorizer.transform(reviews_test)

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, sentiment_train)

In [ ]:
accuracy = classifier.score(X_test, sentiment_test)
print("Accuracy:", accuracy)

Accuracy: 0.81


In [ ]:
new_reviews = ['Old version of python useless', 'Very good effort, but not five stars', 'Clear and concise']
X_new = vectorizer.transform(new_reviews)
print(classifier.predict(X_new))

[0 0 1]


# Esercizi

In [ ]:
# Esercizio 1: Utilizzare le funzioni statistiche di NumPy
# Trovare la media degli importi massimi pagati ogni mese a tutti i dipendenti

print(salary_bonus)

print(np.median(salary_bonus, axis=0))
# se non metto l'asse lo fa solo sul primo
# la mediana è un'altra cosa rispetto alla media

def median(x = [1, 2, 3, 4]): # dove x è un array di elementi
    # molto semplicemente la mediana è un numero, una posizione che indica il punto in cui metà numeri hanno valore
    # superiore rispetto a quel punto, mentre l'altra metà ha un valore inferiore rispetto a quel punto
    n = len(x)
    med = []
    if n % 2 == 0:
        med.append(x[int((n+1)/2)])
    else:
        med.append((x[int(n/2)] + x[int(n/2 + 1)]) / 2)
    return med
print(median())

print(np.average(salary_bonus, axis=0))
print(np.average(salary_bonus, axis=1))
# asse 0 verticale y
# asse 1 orizzontale x

In [40]:
# Esercizio2: Combinare tre serie
data = ['Jeff Russell','Jane Boorman','Tom Heints']
emps_names = pd.Series(data,index=[9001,9002,9003])
emps_names.name = 'names'

data_2 = ['jeff.russell','jane.boorman','tom.heints']
emps_emails = pd.Series(data_2,index=[9001,9002,9003], name = 'emails')

data_ph = [1241231231, 5232348234, 2348234238]
emps_phones = pd.Series(data_ph, index=[9001, 9002, 9003], name = 'phones')
df = pd.concat([emps_names,emps_emails, emps_phones], axis=1)
print(df)

             names        emails      phones
9001  Jeff Russell  jeff.russell  1241231231
9002  Jane Boorman  jane.boorman  5232348234
9003    Tom Heints    tom.heints  2348234238


In [ ]:
# Esercizio 3 Utilizzare join diverse
# aggiungere una nuova riga al df salary in modo che il valore di Empno in questa riga non si trovi nel Dataframe emps
# Successivamente, unite il DataFrame emps con il DF salary in modo che il nuovo df includa
# solo le righe di emps che hanno una corrispondenza nel DF salary
# Unite nuovamente emps con salary in modo che il nuovo df includa tutte le righe di entrambi i dataframe

import pandas as pd
import json
from io import StringIO

data = [ {"Empno":9001,"Salary":3000}, {"Empno":9002,"Salary":2800}, {"Empno":9003,"Salary":2500} ]
json_data = json.dumps(data)
salary = pd.read_json(StringIO((json_data)))
print(salary)

data = [ ['9001','Jeff Russell', 'sales'], ['9002','Jane Boorman', 'sales'], ['9003','Tom Heints', 'sales'] ]
emps = pd.DataFrame(data, columns = ['Empno', 'Name', 'Job'])
column_types = {'Empno': int, 'Name': str, 'Job': str}
emps = emps.astype(column_types)
emps = emps.set_index('Empno')
print(emps)

# Aggiungiamo una riga con Empno = 9999 che non esiste in emps
new_row = pd.DataFrame([{"Empno": 9999, "Salary": 3200}]) # creiamo una nuova riga
salary = pd.concat([salary, new_row], ignore_index=True) # la aggiungiamo a salary

# Unire emps con salary includendo solo le righe di emps che hanno corrispondenza in salary
# Prima mettiamo anche emps con Empno come colonna (non indice) per facilitarne la join
emps_reset = emps.reset_index()  # resettiamo l'indice 
inner_join = pd.merge(emps_reset, salary, on="Empno", how="inner") # facciamo un inner join tra le due tabelle

full_outer_join = pd.merge(emps_reset, salary, on="Empno", how="outer") # full outer per includere tutte le righe di entrambe le tabelle